# Generated by Django 5.1.7 on 2025-06-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('url', models.URLField(blank=True)),
                ('icon', models.ImageField(upload_to='django_portfolio/icons/')),
            ],
        ),
    ]
